### ISSUE TITLE
Want to update README.md file and adding CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by sb-decoder** [ismailbangee/smart-contracts#18]
I want to add how to contribute section and also contributors profile into main README.md file and want to add Code of conduct file.

@ismailbangee Can I add this?

**Comment by ismailbangee** [comment]
Hello

Thank you for taking interest.

What you want to add in it?

**Comment by sb-decoder** [comment]
I want to add beginner friendly contribution guideline and also all of your contributors profile images in your README.md. 
and also adding CODE_OF_CONDUCT

**Comment by ismailbangee** [comment]
Yes you can contribute. Looking forward to it.
