### ISSUE TITLE
Would like to add a smart contract to mint an ERC20 Token

### ISSUE THREAD

**Issue by AnshMinchekar** [ismailbangee/smart-contracts#5]
I would like to add a category/simple smart contract to mint an ERC20 Token.

**Comment by ismailbangee** [comment]
Yes, you can add that smart contract inside the "Helpers" folder but we do already have the ERC20 contract. You can modify it by adding additional functionality or creating any other new contract. 

Do follow the guideline.

https://github.com/ismailbangee/smart-contracts/blob/main/CONTRIBUTING.md
