### ISSUE TITLE
Certificate Authenticity Smart Contract

### ISSUE THREAD

**Issue by ArunBalajiR** [ismailbangee/smart-contracts#9]
I would like to add a smart contract for generating and validating authentic university marksheets/certificates.

**Comment by ismailbangee** [comment]
Hello Arun
Yes you can add it. Kindly follow contribution guidelines

https://github.com/ismailbangee/smart-contracts/blob/main/CONTRIBUTING.md

Thank you.

**Comment by ismailbangee** [comment]
Accepted
